### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by shota-imoto** [shota-imoto/chat-space#12]
# IPアドレス
18.181.25.191

**Comment by mo1015** [comment]
井本さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

**○新規チャットグループ画面、チャット編集画面の見た目が見本と異なる**
<img width="1011" alt="スクリーンショット 2020-04-29 16 00 31" src="https://user-images.githubusercontent.com/62644781/80569805-9f135c00-8a34-11ea-8f5d-d12fdf2d0511.png">
↓見本
<img width="1055" alt="スクリーンショット 2020-04-29 16 18 03" src="https://user-images.githubusercontent.com/62644781/80570036-0af5c480-8a35-11ea-8760-1c5d8398b0cb.png">

**○サイドバーのグループ同士の間隔が空けられていない**
<img width="294" alt="スクリーンショット 2020-04-29 16 09 11" src="https://user-images.githubusercontent.com/62644781/80569819-a63a6a00-8a34-11ea-97d0-5fd0c6caf24f.png">

↓見本
<img width="591" alt="サイドバー見本" src="https://user-images.githubusercontent.com/62644781/80569902-c9651980-8a34-11ea-862b-956f42bde93d.png">

修正でき次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by miyu-yamamoto** [comment]
井本さん、再提出ありがとうございます！
前回修正依頼した部分で実装できない箇所がございますので再度ご確認をお願いします。
(サイドバーのグループ同士の間隔は問題なく修正が確認できました◎)

[修正箇所]
**○新規チャットグループ画面、チャット編集画面の見た目が見本と異なる**

修正でき次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by shota-imoto** [comment]
> 井本さん、再提出ありがとうございます！
> 前回修正依頼した部分で実装できない箇所がございますので再度ご確認をお願いします。
> (サイドバーのグループ同士の間隔は問題なく修正が確認できました◎)
> 
> [修正箇所]
> **○新規チャットグループ画面、チャット編集画面の見た目が見本と異なる**
> <img alt="スクリーンショット 2020-04-30 10 24 27" width="1085" src="https://user-images.githubusercontent.com/59544869/80662696-e1887780-8acc-11ea-924f-0dad94e70f8d.png">
> 
> 修正でき次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
> ※新しいissueを作っていただく必要はありません
> https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

修正いたしました　井本

**Comment by keisukekodama** [comment]
再提出ありがとうございます！
前回修正依頼した部分で実装できない箇所がございますのでデプロイなどを含め再度ご確認をお願いします。

[修正箇所]
**○新規チャットグループ画面、チャット編集画面の見た目が見本と異なる**

<img width="1358" alt="ChatSpace" src="https://user-images.githubusercontent.com/44963290/80669769-28339d00-8ae0-11ea-8283-97810030038c.png">



修正でき次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by shota-imoto** [comment]
コミット→プッシュを忘れておりました・・・
ご確認のほどよろしくお願いいたします。

**Comment by yasunamiura** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、修正箇所ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！
